# Generated by Django 5.0.3 on 2024-03-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
                ('ratings', models.IntegerField(choices=[('Worst', 1), ('Bad', 2), ('Average', 3), ('Good', 4), ('Best', 5)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musician_Pedia.musician')),
            ],
        ),
    ]
