# Generated by Django 5.0.3 on 2024-03-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician_Pedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ratings',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Best')]),
        ),
    ]
