# Generated by Django 5.0.3 on 2024-03-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician_Pedia', '0005_rename_artist_name_album_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ratings',
            new_name='album_ratings',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='album_title',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='age',
            new_name='artist_age',
        ),
    ]
